defaults:
  sudo: true
  continue_on_error: false
  cwd: ../..

jobs:
  - name: netem-nines-bbr-delay-10ms-vs-11ms
    script: netem_nines.py
    params:
      num_clients: 2
      client_names: [flow_a, flow_b]
      client_delays_ms: [10, 11]
      client_ccas: [cubic, bbr]
      client_file_sizes_mbytes: [50, 50]
      snapshot_metrics_source: ss
      ss_sample_interval_ms: 100
      ss_log_file: sslogs/netem_nines/bbr-delay-10ms-vs-11ms.jsonl
      bottleneck_all_client_rate_mbit: 100
      bottleneck_buffer_kbytes: 125

  - name: netem-nines-bbr-delay-10ms-vs-12ms
    script: netem_nines.py
    params:
      num_clients: 2
      client_names: [flow_a, flow_b]
      client_delays_ms: [10, 12]
      client_ccas: [cubic, bbr]
      client_file_sizes_mbytes: [50, 50]
      snapshot_metrics_source: ss
      ss_sample_interval_ms: 100
      ss_log_file: sslogs/netem_nines/bbr-delay-10ms-vs-12ms.jsonl
      bottleneck_all_client_rate_mbit: 100
      bottleneck_buffer_kbytes: 125

  - name: netem-nines-bbr-delay-10ms-vs-13ms
    script: netem_nines.py
    params:
      num_clients: 2
      client_names: [flow_a, flow_b]
      client_delays_ms: [10, 13]
      client_ccas: [cubic, bbr]
      client_file_sizes_mbytes: [50, 50]
      snapshot_metrics_source: ss
      ss_sample_interval_ms: 100
      ss_log_file: sslogs/netem_nines/bbr-delay-10ms-vs-13ms.jsonl
      bottleneck_all_client_rate_mbit: 100
      bottleneck_buffer_kbytes: 125

  - name: netem-nines-bbr-delay-10ms-vs-14ms
    script: netem_nines.py
    params:
      num_clients: 2
      client_names: [flow_a, flow_b]
      client_delays_ms: [10, 14]
      client_ccas: [cubic, bbr]
      client_file_sizes_mbytes: [50, 50]
      snapshot_metrics_source: ss
      ss_sample_interval_ms: 100
      ss_log_file: sslogs/netem_nines/bbr-delay-10ms-vs-14ms.jsonl
      bottleneck_all_client_rate_mbit: 100
      bottleneck_buffer_kbytes: 125

  - name: netem-nines-bbr-delay-10ms-vs-15ms
    script: netem_nines.py
    params:
      num_clients: 2
      client_names: [flow_a, flow_b]
      client_delays_ms: [10, 15]
      client_ccas: [cubic, bbr]
      client_file_sizes_mbytes: [50, 50]
      snapshot_metrics_source: ss
      ss_sample_interval_ms: 100
      ss_log_file: sslogs/netem_nines/bbr-delay-10ms-vs-15ms.jsonl
      bottleneck_all_client_rate_mbit: 100
      bottleneck_buffer_kbytes: 125

  - name: netem-nines-bbr-delay-10ms-vs-16ms
    script: netem_nines.py
    params:
      num_clients: 2
      client_names: [flow_a, flow_b]
      client_delays_ms: [10, 16]
      client_ccas: [cubic, bbr]
      client_file_sizes_mbytes: [50, 50]
      snapshot_metrics_source: ss
      ss_sample_interval_ms: 100
      ss_log_file: sslogs/netem_nines/bbr-delay-10ms-vs-16ms.jsonl
      bottleneck_all_client_rate_mbit: 100
      bottleneck_buffer_kbytes: 125

  - name: netem-nines-bbr-delay-10ms-vs-17ms
    script: netem_nines.py
    params:
      num_clients: 2
      client_names: [flow_a, flow_b]
      client_delays_ms: [10, 17]
      client_ccas: [cubic, bbr]
      client_file_sizes_mbytes: [50, 50]
      snapshot_metrics_source: ss
      ss_sample_interval_ms: 100
      ss_log_file: sslogs/netem_nines/bbr-delay-10ms-vs-17ms.jsonl
      bottleneck_all_client_rate_mbit: 100
      bottleneck_buffer_kbytes: 125

  - name: netem-nines-bbr-delay-10ms-vs-18ms
    script: netem_nines.py
    params:
      num_clients: 2
      client_names: [flow_a, flow_b]
      client_delays_ms: [10, 18]
      client_ccas: [cubic, bbr]
      client_file_sizes_mbytes: [50, 50]
      snapshot_metrics_source: ss
      ss_sample_interval_ms: 100
      ss_log_file: sslogs/netem_nines/bbr-delay-10ms-vs-18ms.jsonl
      bottleneck_all_client_rate_mbit: 100
      bottleneck_buffer_kbytes: 125

  - name: netem-nines-bbr-delay-10ms-vs-19ms
    script: netem_nines.py
    params:
      num_clients: 2
      client_names: [flow_a, flow_b]
      client_delays_ms: [10, 19]
      client_ccas: [cubic, bbr]
      client_file_sizes_mbytes: [50, 50]
      snapshot_metrics_source: ss
      ss_sample_interval_ms: 100
      ss_log_file: sslogs/netem_nines/bbr-delay-10ms-vs-19ms.jsonl
      bottleneck_all_client_rate_mbit: 100
      bottleneck_buffer_kbytes: 125
